---
development:
  cloud_name: hxbuuwdcd
  api_key: '898238593348119'
  api_secret: k-Do_hoZfLy8OctkPTI5jv-D9Vc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hxbuuwdcd
  api_key: '898238593348119'
  api_secret: k-Do_hoZfLy8OctkPTI5jv-D9Vc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hxbuuwdcd
  api_key: '898238593348119'
  api_secret: k-Do_hoZfLy8OctkPTI5jv-D9Vc
  enhance_image_tag: true
  static_image_support: false
